version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "3030:3030"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development

  docs:
    build:
      context: ./docs
    ports:
      - "5173:5173"
    volumes:
      - ./docs:/app
      - /app/node_modules
    command: npm run docs:dev
    environment:
      - NODE_ENV=development
